version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: manage_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-your-secret-key-here-change-in-production
      - DATABASE_URL=postgres://postgres:password@db:5432/manage_system_db
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: 