# Generated by Django 5.2.3 on 2025-06-27 14:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_date", models.DateField()),
                ("reviewer", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True, null=True)),
                ("goals", models.TextField(blank=True, null=True)),
                ("achievements", models.TextField(blank=True, null=True)),
                ("areas_for_improvement", models.TextField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date", "employee__name"],
                "indexes": [
                    models.Index(
                        fields=["employee"], name="performance_employe_46ef83_idx"
                    ),
                    models.Index(
                        fields=["review_date"], name="performance_review__10a908_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="performance_rating_294d36_idx"
                    ),
                ],
            },
        ),
    ]
