# Generated by Django 5.2.3 on 2025-06-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employee__name"],
                "indexes": [
                    models.Index(
                        fields=["employee"], name="attendance__employe_c89dc0_idx"
                    ),
                    models.Index(fields=["date"], name="attendance__date_61f2e1_idx"),
                    models.Index(
                        fields=["status"], name="attendance__status_132c06_idx"
                    ),
                    models.Index(
                        fields=["employee", "date"],
                        name="attendance__employe_08d913_idx",
                    ),
                ],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
